# @package _global_
defaults:
  - override /hydra/launcher: basic

wandb:
  enabled: false
  config:
    project: cloudgripper-wm
    name: ${output_model_name}
    id: ${subdir}
    resume: allow
    log_model: false
